language: node_js
node_js:
- 8.1
cache: yarn

install:
- yarn

script:
- yarn test
- yarn build

before_deploy:
  - yarn global add netlify-cli

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./dist
  skip_cleanup: true
  on:
    branch: master
